const Shift = require('../models/Shift');
const Employee = require('../models/Employee');
const User = require('../models/User');
const logger = require('../config/logger');

const pad = (n) => String(n).padStart(2, '0');

const parseWorkDays = () => {
  const raw = process.env.AUTO_ROSTER_WORK_DAYS || '1,2,3,4,5';
  return raw
    .split(',')
    .map((d) => parseInt(d.trim(), 10))
    .filter((d) => Number.isInteger(d) && d >= 0 && d <= 6);
};

const parseTime = (timeString, fallbackHour, fallbackMinute) => {
  if (!timeString || typeof timeString !== 'string' || !timeString.includes(':')) {
    return { hour: fallbackHour, minute: fallbackMinute };
  }

  const [hourRaw, minuteRaw] = timeString.split(':');
  const hour = parseInt(hourRaw, 10);
  const minute = parseInt(minuteRaw, 10);

  if (!Number.isInteger(hour) || !Number.isInteger(minute)) {
    return { hour: fallbackHour, minute: fallbackMinute };
  }

  return { hour, minute };
};

const availabilityKeyByDay = {
  0: 'sunday',
  1: 'monday',
  2: 'tuesday',
  3: 'wednesday',
  4: 'thursday',
  5: 'friday',
  6: 'saturday',
};

const buildDateWithTime = (date, hour, minute) => {
  const d = new Date(date);
  d.setHours(hour, minute, 0, 0);
  return d;
};

const getMonthBoundaries = (year, monthIndex) => {
  const monthStart = new Date(year, monthIndex, 1, 0, 0, 0, 0);
  const monthEnd = new Date(year, monthIndex + 1, 0, 23, 59, 59, 999);
  return { monthStart, monthEnd };
};

const generateMonthlyRoster = async ({ year, month } = {}) => {
  const now = new Date();
  const targetYear = Number.isInteger(year) ? year : now.getFullYear();
  const targetMonthIndex = Number.isInteger(month) ? month - 1 : now.getMonth();

  if (targetMonthIndex < 0 || targetMonthIndex > 11) {
    throw new Error('Invalid month value for roster generation');
  }

  const cycleKey = `${targetYear}-${pad(targetMonthIndex + 1)}`;
  const { monthStart, monthEnd } = getMonthBoundaries(targetYear, targetMonthIndex);

  const workDays = parseWorkDays();
  const defaultStart = parseTime(process.env.AUTO_ROSTER_SHIFT_START || '09:00', 9, 0);
  const defaultEnd = parseTime(process.env.AUTO_ROSTER_SHIFT_END || '17:00', 17, 0);

  const schedulerActor = await User.findOne({
    role: { $in: ['admin', 'manager'] },
    isActive: true,
  }).select('_id');

  if (!schedulerActor) {
    logger.warn(`Monthly roster skipped for ${cycleKey}: no active admin/manager found`);
    return { cycleKey, created: 0, skipped: 0, removed: 0 };
  }

  const employees = await Employee.find({ status: 'active' })
    .populate('user', 'isActive firstName lastName')
    .select('_id user availability');

  const activeEmployees = employees.filter((e) => e.user && e.user.isActive !== false);

  const removedResult = await Shift.deleteMany({
    autoGenerated: true,
    generationCycle: cycleKey,
  });

  let created = 0;
  let skipped = 0;

  for (let date = new Date(monthStart); date <= monthEnd; date.setDate(date.getDate() + 1)) {
    const day = date.getDay();
    if (!workDays.includes(day)) {
      continue;
    }

    for (const employee of activeEmployees) {
      const availabilityKey = availabilityKeyByDay[day];
      const dayAvailability = employee.availability?.[availabilityKey] || null;

      if (dayAvailability && dayAvailability.available === false) {
        skipped += 1;
        continue;
      }

      const startTimeSource = dayAvailability?.start || process.env.AUTO_ROSTER_SHIFT_START || '09:00';
      const endTimeSource = dayAvailability?.end || process.env.AUTO_ROSTER_SHIFT_END || '17:00';

      const startParts = parseTime(startTimeSource, defaultStart.hour, defaultStart.minute);
      const endParts = parseTime(endTimeSource, defaultEnd.hour, defaultEnd.minute);

      const startTime = buildDateWithTime(date, startParts.hour, startParts.minute);
      const endTime = buildDateWithTime(date, endParts.hour, endParts.minute);

      if (endTime <= startTime) {
        skipped += 1;
        continue;
      }

      const hasConflict = await Shift.findOne({
        employee: employee._id,
        status: { $nin: ['cancelled'] },
        $or: [
          { startTime: { $lte: startTime }, endTime: { $gt: startTime } },
          { startTime: { $lt: endTime }, endTime: { $gte: endTime } },
          { startTime: { $gte: startTime }, endTime: { $lte: endTime } },
        ],
      }).select('_id');

      if (hasConflict) {
        skipped += 1;
        continue;
      }

      const monthName = startTime.toLocaleString('en-US', { month: 'long' });
      await Shift.create({
        title: `${monthName} Auto Shift`,
        description: `Automatically generated monthly roster for ${cycleKey}`,
        employee: employee._id,
        startTime,
        endTime,
        type: 'regular',
        status: 'scheduled',
        autoGenerated: true,
        generationCycle: cycleKey,
        notes: 'Auto-generated monthly roster',
        createdBy: schedulerActor._id,
      });

      created += 1;
    }
  }

  logger.info(`Monthly roster generation completed for ${cycleKey}: created=${created}, skipped=${skipped}, removed=${removedResult.deletedCount}`);
  return {
    cycleKey,
    created,
    skipped,
    removed: removedResult.deletedCount,
  };
};

module.exports = {
  generateMonthlyRoster,
};
